Repository omichel/webots-doc, pull requests merged in 2018-03, with the labels that each got.

#669 Fix Bias in Doc
  reference/lensflare.md
Labels: incorrect

#672 Add a "why not contribute?" banner to documentation
  css/images/github.png
  css/webots-doc.css
  js/viewer.js
Labels: enhancement

#673 Use querySelector API where possible
  js/viewer.js
Labels: obsolete

#676 Fix Code Highlighting
  guide/cpp-java-python.md
  js/viewer.js
  reference/motion.md
  robotis-op2/gait-manager.md
  robotis-op2/motion-manager.md
  robotis-op2/symmetry.md
  robotis-op2/vision-manager.md
  robotis-op2/visualtracking.md
Labels: incorrect

#679 Fix icons autocrop
  guide/images/robots/aibo-ers7/icon.png
  guide/images/robots/altino/icon.png
  guide/images/robots/atlas/icon.png
  guide/images/robots/bb8/icon.png
  guide/images/robots/bioloid/icon.png
  guide/images/robots/boebot/icon.png
  guide/images/robots/create/icon.png
  guide/images/robots/darwin-op/icon.png
  guide/images/robots/elisa3/icon.png
  guide/images/robots/epuck/icon.png
  guide/images/robots/firebird6/icon.png
  guide/images/robots/hemisson/icon.png
  guide/images/robots/hoap2/icon.png
  guide/images/robots/icub/icon.png
  guide/images/robots/khepera1/icon.png
  guide/images/robots/khepera2/icon.png
  guide/images/robots/khepera3/icon.png
  guide/images/robots/khepera4/icon.png
  guide/images/robots/khr-2hv/icon.png
  guide/images/robots/khr-3hv/icon.png
  guide/images/robots/koala/icon.png
  guide/images/robots/mantis/icon.png
  guide/images/robots/microbot/icon.png
  guide/images/robots/mindstorms/icon.png
  guide/images/robots/nao/icon.png
  guide/images/robots/pioneer-3at/icon.png
  guide/images/robots/pioneer-3dx/icon.png
  guide/images/robots/pioneer2/icon.png
  guide/images/robots/pr2/icon.png
  guide/images/robots/puma/icon.png
  guide/images/robots/robotis-op2/icon.png
  guide/images/robots/shrimp/icon.png
  guide/images/robots/surveyor/icon.png
  guide/images/robots/thymio2/icon.png
  guide/images/robots/youbot/icon.png
Labels: incorrect

#674 Feature Charts
  css/webots-doc.css
  doc.php
  guide/controller-plugin.md
  guide/cpp-java-python.md
  guide/images/api_overview.png
  guide/images/controller_plugin.png
  guide/images/tutorial_4_wheels_highlevel.png
  guide/images/tutorial_4_wheels_lowlevel.png
  guide/images/tutorial_compound_solid.png
  guide/images/tutorial_def_use_shape.png
  guide/images/tutorial_feedback_loop.png
  guide/images/tutorial_solid.png
  guide/tutorial-2-modification-of-the-environment-20-minutes.md
  guide/tutorial-4-more-about-controllers-20-minutes.md
  guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes.md
  guide/tutorial-6-4-wheels-robot.md
  index.html
  js/showdown-extensions.js
  js/viewer.js
  local_exporter.py
  reference/chart.md
  reference/execution-scheme.md
  reference/images/motor_control.png
  reference/images/node_hierarchy.png
  reference/images/physics_execution_scheme.png
  reference/motor.md
  src/dia/Makefile
  src/dia/api_overview.dia
  src/dia/controller_plugin.dia
  src/dia/motor_control.dia
  src/dia/node_hierarchy.dia
  src/dia/physics_execution_scheme.dia
  src/dia/tutorial_4_wheels_highlevel.dia
  src/dia/tutorial_4_wheels_lowlevel.dia
  src/dia/tutorial_ackermann_vehicle.dia
  src/dia/tutorial_compound_solid.dia
  src/dia/tutorial_def_use_shape.dia
  src/dia/tutorial_feedback_loop.dia
  src/dia/tutorial_solid.dia
  tests/test_hyperlinks.py
  tests/test_paragraphs.py
Labels: enhancement

#681 Add a description for the robot list
  guide/robots.md
Labels: enhancement

#680 Document the current status of the e-puck 2
  guide/epuck.md
  guide/images/robots/epuck/e-puck2.wbt.png
  guide/images/robots/epuck/epuck2.png
  tests/test_titles.py
Labels: enhancement

#686 Hotfix wrong merges
  guide/controller-programming.md
  guide/cpp-java-python.md
  guide/debugging-c-cpp-controllers.md
  guide/general-faq.md
  guide/images/reset-simulation-button.png
  guide/matlab.md
  guide/modeling.md
  guide/preferences.md
  guide/programming.md
  guide/the-user-interface.md
  guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  guide/tutorial-4-more-about-controllers-20-minutes.md
  guide/using-numerical-optimization-methods.md
  guide/using-visual-cpp-with-webots.md
  index.html
  js/showdown-extensions.js
  reference/brake.md
  reference/camera.md
  reference/cpp-api.md
  reference/images/track_bounding_object.png
  reference/java-api.md
  reference/joystick.md
  reference/matlab-api.md
  reference/motor.md
  reference/positionsensor.md
  reference/proto-example.md
  reference/python-api.md
  reference/robot.md
  reference/ros-api.md
  reference/speaker.md
  reference/supervisor.md
  reference/track.md
  robotis-op2/examples.md
  robotis-op2/symmetry.md
  robotis-op2/using-remote-control-from-robot-window.md
Labels: incorrect

#689 Fix Node Hierarchy
  reference/accelerometer.md
  reference/camera.md
  reference/compass.md
  reference/connector.md
  reference/device.md
  reference/display.md
  reference/distancesensor.md
  reference/emitter.md
  reference/gps.md
  reference/gyro.md
  reference/inertialunit.md
  reference/led.md
  reference/lidar.md
  reference/lightsensor.md
  reference/pen.md
  reference/radar.md
  reference/rangefinder.md
  reference/receiver.md
  reference/speaker.md
  reference/touchsensor.md
Labels: incorrect

#678 Remove Reference to "--enable-ogre-warnings"
  guide/starting-webots.md
Labels: obsolete

#682 youtube movies in doc
  css/webots-doc.css
  guide/bb8.md
  guide/bioloid.md
  guide/create.md
  guide/darwin-op.md
  guide/epuck.md
  guide/hoap2.md
  guide/ipr.md
  guide/khepera4.md
  guide/khr-2hv.md
  guide/khr-3hv.md
  guide/mantis.md
  guide/nao.md
  guide/pioneer-3at.md
  guide/pioneer-3dx.md
  guide/portal.md
  guide/pr2.md
  guide/puma.md
  guide/robotis-op2.md
  guide/shrimp.md
  guide/thymio2.md
  guide/youbot.md
  js/viewer.js
Labels: enhancement

#693 Fix mispelling of Robotis OP2
  guide/menu.md
  guide/robotis-op2.md
  guide/robots.md
Labels: incorrect

#695 WREN: Remove References to OpenGL with Physics Plugins
  guide/how-to.md
  guide/images/contact_points.png
  guide/programming.md
  reference/callback-functions.md
  reference/examples.md
Labels: obsolete

#624 WREN
  guide/how-to.md
  guide/images/camera_compositor.png
  guide/images/contact_points.png
  guide/programming.md
  guide/starting-webots.md
  guide/webots-devices.md
  reference/appearance.md
  reference/callback-functions.md
  reference/camera.md
  reference/chart.md
  reference/composedcubemaptexture.md
  reference/composedshader.md
  reference/examples.md
  reference/images/environment-mapping.png
  reference/images/lens_flare.png
  reference/imagetexture.md
  reference/lensflare.md
  reference/lidar.md
  reference/light.md
  reference/menu.md
  reference/multitexture.md
  reference/nodes-and-api-functions.md
  reference/rangefinder.md
  reference/shaderpart.md
  reference/uniform.md
Labels: obsolete

#691 Fix the contribute banner on macOS when embedded in Webots
  css/webots-doc.css
Labels: incorrect

#699 Create new robot pages.
  guide/blimp.md
  guide/demo-directory.md
  guide/ghostdog.md
  guide/images/robots/blimp/blimp.wbt.png
  guide/images/robots/blimp/icon.png
  guide/images/robots/blimp/model.png
  guide/images/robots/ghostdog/ghostdog.wbt.png
  guide/images/robots/ghostdog/icon.png
  guide/images/robots/ghostdog/model.png
  guide/images/robots/qrio/icon.png
  guide/images/robots/qrio/model.png
  guide/images/robots/qrio/qrio.wbt.png
  guide/images/robots/salamander/icon.png
  guide/images/robots/salamander/model.png
  guide/images/robots/salamander/salamander.wbt.png
  guide/images/robots/sojourner/icon.png
  guide/images/robots/sojourner/model.png
  guide/images/robots/sojourner/sojourner.wbt.png
  guide/images/robots/yamor/icon.png
  guide/images/robots/yamor/model.png
  guide/images/robots/yamor/yamor.wbt.png
  guide/menu.md
  guide/qrio.md
  guide/robots.md
  guide/salamander.md
  guide/sojourner.md
  guide/yamor.md
Labels: enhancement

#701 Fixed name
  guide/icub.md
Labels: incorrect

#702 Fixed English
  guide/pr2.md
Labels: incorrect

#707 Merge master to webots r2018a revision 1
  css/webots-doc.css
  guide/icub.md
  guide/pr2.md
  reference/chart.md
  reference/menu.md
  reference/node-chart.md
Labels: update

#710 Add Movies in Automobile Doc
  automobile/introduction.md
  automobile/openstreetmap-importer.md
  automobile/sumo-interface.md
Labels: enhancement

#712 Fix Pioneer2 images alpha.
  guide/images/robots/pioneer2/icon.png
  guide/images/robots/pioneer2/model.png
Labels: incorrect

#716 Update description of robot menu items
  guide/the-user-interface.md
Labels: update

#714 Add a controller for the Mantis robot
  guide/images/robots/koala/mantis.wbt.png
  guide/images/robots/mantis/mantis.wbt.png
  guide/mantis.md
Labels: enhancement

#718 Remove ROS 'custom' Simulation
  guide/using-ros.md
Labels: obsolete

#717 Add missing OSM importer dependency on Ubuntu 14.04
  automobile/openstreetmap-importer.md
Labels: update

#720 Fix whitespace wrapping for code in paragraphs
  css/webots-doc.css
Labels: incorrect

#723 Merge master into r2018a revision 1
  automobile/introduction.md
  automobile/openstreetmap-importer.md
  automobile/sumo-interface.md
  css/webots-doc.css
Labels: update

#727 Fix scroll bar issues for small view widths.
  css/webots-doc.css
Labels: incorrect

#730 Fixed the documentation of the quit menu items
  guide/the-user-interface.md
Labels: enhancement

#733 Merge master into develop
  automobile/introduction.md
  automobile/openstreetmap-importer.md
  automobile/sumo-interface.md
  css/webots-doc.css
  guide/images/robots/koala/mantis.wbt.png
  guide/images/robots/mantis/mantis.wbt.png
  guide/images/robots/pioneer2/icon.png
  guide/images/robots/pioneer2/model.png
  guide/mantis.md
  guide/the-user-interface.md
  guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes.md
  guide/using-ros.md
  reference/camera.md
  reference/distancesensor.md
  reference/inertialunit.md
  reference/jointparameters.md
  reference/lidar.md
  reference/lightsensor.md
  reference/plane.md
  reference/pointlight.md
  reference/propeller.md
  reference/proto.md
  reference/rangefinder.md
  reference/spotlight.md
  reference/texturetransform.md
  reference/transform.md
  tests/test_md_files.py
Labels: update

#734 Document exception to the valid use of multiple IS statements for the same PROTO field
  reference/proto-definition.md
Labels: enhancement

#736 Add License URL
  reference/proto-design-guidelines.md
  reference/proto-example.md
Labels: enhancement

#738 Automatic index
  js/viewer.js
Labels: enhancement

#739 Fix index which cannot take into consideration a double level jump.
  js/viewer.js
Labels: incorrect

#741 Enhancement of the index location and look
  css/webots-doc.css
  js/viewer.js
Labels: enhancement

#742 Document the robot PROTO nodes and their fields
  guide/aibo-ers7.md
  guide/altino.md
  guide/atlas.md
  guide/bb8.md
  guide/bioloid.md
  guide/blimp.md
  guide/boebot.md
  guide/create.md
  guide/elisa3.md
  guide/epuck.md
  guide/firebird6.md
  guide/ghostdog.md
  guide/hemisson.md
  guide/hoap2.md
  guide/ipr.md
  guide/khepera1.md
  guide/khepera2.md
  guide/khepera3.md
  guide/khepera4.md
  guide/khr-2hv.md
  guide/khr-3hv.md
  guide/koala.md
  guide/mantis.md
  guide/microbot.md
  guide/mindstorms.md
  guide/nao.md
  guide/pioneer-3at.md
  guide/pioneer-3dx.md
  guide/pioneer2.md
  guide/portal.md
  guide/pr2.md
  guide/puma.md
  guide/qrio.md
  guide/robotis-op2.md
  guide/salamander.md
  guide/shrimp.md
  guide/sojourner.md
  guide/surveyor.md
  guide/thymio2.md
  guide/yamor.md
  guide/youbot.md
Labels: enhancement
