Repository omichel/webots-doc, pull requests merged in 2018-04, with the labels that each got.

#752 Hotfix: add missing speed unit in the tutorial 4.
  guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: incorrect

#746 Document the missing missing commercial sensors
  guide/images/sensors/hokuyo_urg_04lx.png
  guide/images/sensors/hokuyo_urg_04lx_icon.png
  guide/images/sensors/hokuyo_urg_04lx_ug01.png
  guide/images/sensors/hokuyo_urg_04lx_ug01_icon.png
  guide/images/sensors/hokuyo_utm_30lx.png
  guide/images/sensors/hokuyo_utm_30lx_icon.png
  guide/images/sensors/kinect.png
  guide/images/sensors/kinect_icon.png
  guide/lidar-sensors.md
  guide/menu.md
  guide/range-finder-sensors.md
  guide/sensors.md
Labels: enhancement

#754 Merge master to webots r2018a revision 2
  guide/images/sensors/hokuyo_urg_04lx.png
  guide/images/sensors/hokuyo_urg_04lx_icon.png
  guide/images/sensors/hokuyo_urg_04lx_ug01.png
  guide/images/sensors/hokuyo_urg_04lx_ug01_icon.png
  guide/images/sensors/hokuyo_utm_30lx.png
  guide/images/sensors/hokuyo_utm_30lx_icon.png
  guide/images/sensors/kinect.png
  guide/images/sensors/kinect_icon.png
  guide/lidar-sensors.md
  guide/menu.md
  guide/range-finder-sensors.md
  guide/robotis-op2.md
  guide/sensors.md
  guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: update

#758 Add Node Definition to Glossary
  reference/glossary.md
Labels: enhancement

#761 Improve management of italic and bold fonts.
  css/fonts/Roboto-Bold.ttf
  css/fonts/Roboto-BoldItalic.ttf
  css/fonts/Roboto-Italic.ttf
  css/fonts/Roboto-Regular.ttf
  css/webots-doc.css
Labels: enhancement

#762 Fix DistanceSensor Documentation
  reference/accelerometer.md
  reference/compass.md
  reference/distancesensor.md
  reference/gyro.md
  reference/inertialunit.md
  reference/lightsensor.md
  reference/touchsensor.md
Labels: incorrect

#766 Update Hokuyo Names
  guide/lidar-sensors.md
Labels: update

#770 Updated to R2018a revision 2
  js/showdown-extensions.js
Labels: update

#772 Fix recently added ESLint issues
  js/viewer.js
Labels: enhancement

#774 Fix Remaining WREN Cleanup
  reference/appearance.md
Labels: incorrect

#776 Merge webots-r2018a-revision-2 to develop
  js/viewer.js
  reference/accelerometer.md
  reference/compass.md
  reference/distancesensor.md
  reference/gyro.md
  reference/inertialunit.md
  reference/lightsensor.md
  reference/supervisor.md
  reference/touchsensor.md
Labels: update

#777 Feature Sensors in SUMO Vehicles.
  automobile/car.md
  automobile/images/sumo_interface_example.png
  automobile/sumo-interface-example.md
  automobile/sumo-interface.md
Labels: enhancement

#744 Feature Extend PROTO
  guide/the-scene-tree.md
Labels: enhancement

#771 Scene Tree Context Menu
  guide/the-scene-tree.md
Labels: enhancement

#780 Dynamic load of dependencies
  .gitignore
  README.md
  dependencies.txt
  doc.php
  index.template.html
  js/viewer.js
  local_exporter.py
Labels: enhancement

#782 Merge master to webots-r2018a-revision-2
  .gitignore
  README.md
  dependencies.txt
  doc.php
  guide/epuck.md
  guide/robotis-op2.md
  index.template.html
  js/viewer.js
  local_exporter.py
Labels: update

#783 Merge webots r2018a revision 2 to develop
  .gitignore
  README.md
  dependencies.txt
  doc.php
  guide/epuck.md
  guide/robotis-op2.md
  index.template.html
  js/viewer.js
  local_exporter.py
Labels: update

#784 Fix local exporter to be called from another directory.
  local_exporter.py
Labels: incorrect

#785 Merge master to webots r2018a revision 2
  local_exporter.py
Labels: update

#786 Merge webots r2018a revision 2 to develop
  local_exporter.py
Labels: update

#791 Fix Vertical Figure > Img Scrollbar
  css/webots-doc.css
Labels: incorrect

#794 Fix wrong chart display
  css/webots-doc.css
Labels: incorrect

#792 Fix word wrapping on code blocks in embedded doc
  css/webots-doc.css
Labels: incorrect

#796 Merge master into webots-r2018-revision-2
  css/webots-doc.css
  guide/installation-procedure.md
Labels: update

#797 Merge r2018a rev2 into master
  guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  guide/tutorial-4-more-about-controllers-20-minutes.md
  js/showdown-extensions.js
  reference/proto-definition.md
Labels: update

#802 Drop obsolete reference to SPEED_UNIT
  guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: incorrect

#804 Improved NAO doc
  guide/nao.md
Labels: enhancement

#805 Mouse API to Get Coordinate in Screen Space
  reference/java-api.md
  reference/mouse.md
  reference/python-api.md
  reference/ros-api.md
Labels: enhancement

#807 Merge master to webots r2018a revision 3
  guide/nao.md
Labels: update

#809 Extended Context Menu
  guide/images/copy-button.png
  guide/images/cut-button.png
  guide/images/delete-button.png
  guide/images/help-button.png
  guide/images/paste-button.png
  guide/images/reset-button.png
  guide/the-scene-tree.md
  guide/the-user-interface.md
Labels: enhancement

#813 Fix matlab robot custom data function names
  reference/matlab-api.md
Labels: incorrect

#781 Physically-Based Rendering
  reference/appearance.md
  reference/background.md
  reference/cubemap.md
  reference/images/pbrappearance.png
  reference/menu.md
  reference/node-chart.md
  reference/nodes-and-api-functions.md
  reference/pbrappearance.md
Labels: enhancement
