Repository omichel/webots-doc, pull requests merged in 2018-06, with the labels that each got.

#841 Tab component
  automobile/appendix.md
  automobile/car-library.md
  automobile/cpp-java-and-python-wrappers-of-the-automobile-libraries.md
  automobile/cpp-libraries.md
  automobile/driver-library.md
  automobile/java-libraries.md
  automobile/menu.md
  automobile/python-libraries.md
  automobile/ros-support.md
  automobile/ros_automobile-controller.md
  css/webots-doc.css
  guide/cpp-java-python.md
  js/showdown-extensions.js
  js/viewer.js
  reference/accelerometer.md
  reference/brake.md
  reference/camera.md
  reference/compass.md
  reference/connector.md
  reference/cpp-api.md
  reference/device.md
  reference/differentialwheels.md
  reference/display.md
  reference/distancesensor.md
  reference/emitter.md
  reference/gps.md
  reference/gyro.md
  reference/inertialunit.md
  reference/java-api.md
  reference/joystick.md
  reference/keyboard.md
  reference/led.md
  reference/lidar.md
  reference/lightsensor.md
  reference/matlab-api.md
  reference/menu.md
  reference/motion.md
  reference/motor.md
  reference/mouse.md
  reference/other-apis.md
  reference/pen.md
  reference/positionsensor.md
  reference/python-api.md
  reference/radar.md
  reference/rangefinder.md
  reference/receiver.md
  reference/robot.md
  reference/ros-api.md
  reference/speaker.md
  reference/supervisor.md
  reference/touchsensor.md
  reference/utility-functions.md
  tests/test_paragraphs.py
Labels: enhancement

#849 Update supported ROS versions
  guide/tutorial-7-using-ros.md
Labels: update

#852 Fix mistakes in Reference Manual
  reference/accelerometer.md
  reference/brake.md
  reference/camera.md
  reference/compass.md
  reference/device.md
  reference/display.md
  reference/distancesensor.md
  reference/emitter.md
  reference/gps.md
  reference/gyro.md
  reference/inertialunit.md
  reference/joystick.md
  reference/keyboard.md
  reference/led.md
  reference/lidar.md
  reference/lightsensor.md
  reference/motor.md
  reference/mouse.md
  reference/positionsensor.md
  reference/radar.md
  reference/rangefinder.md
  reference/touchsensor.md
Labels: incorrect

#855 Remove documentation about Ubuntu 14.04
  automobile/openstreetmap-importer.md
  guide/installation-procedure.md
  guide/system-requirements.md
  guide/using-python.md
  local_exporter.py
Labels: obsolete

#859 Fix mouse ROS API
  reference/mouse.md
Labels: incorrect

#860 Remove wrong superclass from Joystick and Keyboard classes
  reference/joystick.md
  reference/keyboard.md
Labels: incorrect

#863 Typo in car.h: WBU_CAR_COMBUTSION_ENGINE
  automobile/car-library.md
Labels: incorrect

#861 Let the doc match with the real nodes.h (and derived files) state
  reference/supervisor.md
Labels: incorrect

#865 Cleanup API Enum/Define
  automobile/car-library.md
  automobile/driver-library.md
  reference/distancesensor.md
  reference/gps.md
  reference/keyboard.md
  reference/supervisor.md
  reference/touchsensor.md
Labels: enhancement

#864 R2018b blog post
  blog/Webots-2018-b-release.md
  blog/images/context_menu.png
  blog/images/new_objects.png
  blog/images/reset.png
  blog/images/screenshot-html-export-dialog.png
  blog/images/telephone.png
  blog/images/webots_night.png
  blog/menu.md
  css/webots-doc.css
  js/viewer.js
Labels: enhancement, update

#871 Fix Vehicle typedef Names.
  automobile/car-library.md
  automobile/driver-library.md
Labels: enhancement

#872 Document New Mouse Functions
  reference/mouse.md
Labels: enhancement

#874 Merge webots-r2018a-revision-3 to develop
  guide/preferences.md
  guide/webots-license-system.md
Labels: update

#876 Document the camera recognition feature
  reference/camera.md
  reference/images/camera_recognition.png
Labels: enhancement

#878 Add a note about not using PBR in Display nodes
  reference/display.md
Labels: enhancement

#882 Update ros controller arguments
  guide/using-ros.md
Labels: enhancement

#884 Fix nodes chart
  reference/node-chart.md
Labels: incorrect

#883 Fix Vehicle Libraries Path
  guide/using-visual-cpp-with-webots.md
Labels: incorrect

#875 Cleanup Node List
  reference/supervisor.md
Labels: incorrect, obsolete

#886 Update nodes-and-keywords.md page
  reference/node-chart.md
  reference/nodes-and-keywords.md
Labels: update

#887 Fix alphabetical order of nodes in list
  reference/supervisor.md
Labels: enhancement

#888 Add a node about physical behaviors of non top robot nodes
  reference/robot.md
Labels: enhancement

#893 Remove line width
  guide/preferences.md
Labels: obsolete

#892 Update mouse events
  guide/how-to.md
  reference/robot.md
Labels: enhancement

#896 Update tutorials
  guide/tutorial-2-modification-of-the-environment-20-minutes.md
Labels: obsolete

#895 Regenerate objects docs
  guide/object-buildings.md
  guide/object-road.md
  guide/object-street-furniture.md
  guide/object-traffic.md
  guide/object-trees.md
Labels: update

#898 Document SHIFT+right click shortcut
  guide/the-3d-window.md
Labels: enhancement

#904 Document the installation of make and g++ packages
  guide/installation-procedure.md
Labels: enhancement

#901 Add link to node reference from guide
  automobile/ackermannvehicle.md
  automobile/car-and-driver-libraries.md
  automobile/car.md
  automobile/ch-vens.md
  automobile/city-night.md
  automobile/driver-library.md
  automobile/scenario-creation-tutorial.md
  automobile/sumo-exporter.md
  automobile/sumo-interface.md
  automobile/vehiclewheel.md
  guide/aibo-ers7.md
  guide/blimp.md
  guide/boebot.md
  guide/camera-sensors.md
  guide/controller-plugin.md
  guide/controller-programming.md
  guide/cpp-java-python.md
  guide/create.md
  guide/epuck.md
  guide/going-further.md
  guide/hemisson.md
  guide/introduction-to-webots.md
  guide/khepera1.md
  guide/matlab.md
  guide/microbot.md
  guide/modeling.md
  guide/object-solids.md
  guide/pioneer-3at.md
  guide/pioneer-3dx.md
  guide/preferences.md
  guide/programming.md
  guide/range-finder-sensors.md
  guide/robotis-op2.md
  guide/samples-demos.md
  guide/samples-devices.md
  guide/samples-geometries.md
  guide/samples-howto.md
  guide/speed-performance.md
  guide/starting-webots-remotely-ssh.md
  guide/supervisor-programming.md
  guide/the-scene-tree.md
  guide/the-standard-file-hierarchy-of-a-project.md
  guide/the-user-interface.md
  guide/transfer-to-your-own-robot.md
  guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  guide/tutorial-2-modification-of-the-environment-20-minutes.md
  guide/tutorial-3-appearance-15-minutes.md
  guide/tutorial-4-more-about-controllers-20-minutes.md
  guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes.md
  guide/tutorial-6-4-wheels-robot.md
  guide/tutorial-7-using-ros.md
  guide/using-cpp.md
  guide/using-numerical-optimization-methods.md
  guide/web-animation.md
  guide/web-scene.md
  guide/webots-plugin.md
  guide/yamor.md
  tests/test_lists.py
Labels: enhancement

#902 Cleanup requried package for physic plugins
  guide/installation-procedure.md
Labels: obsolete

#906 Regenerate robot components
  guide/scenes/aibo-ers7/aibo-ers7.meta.json
  guide/scenes/aibo-ers7/aibo-ers7.x3d
  guide/scenes/pioneer-3dx/pioneer-3dx.meta.json
  guide/scenes/pioneer-3dx/pioneer-3dx.x3d
  guide/scenes/salamander/salamander.meta.json
  guide/scenes/salamander/salamander.x3d
Labels: enhancement

#908 Update Physics Plugin Examples
  reference/examples.md
Labels: obsolete

#912 Improve sample keyword
  guide/how-to.md
Labels: enhancement

#911 Update Screenshots
  guide/images/field_editor.png
  guide/images/html-export-dialog.png
  guide/images/main_window.png
  guide/images/rendering_device_window.png
  guide/images/scene_tree1.png
  guide/images/speedometer.png
  guide/images/tutorial_appearance.png
  guide/images/tutorial_ball.png
  guide/images/tutorial_def_use.png
  guide/images/tutorial_dumbbell.png
  guide/images/tutorial_gui.png
  guide/images/tutorial_walls.png
  guide/images/web-animation.png
  guide/images/web-scene.png
  guide/the-3d-window.md
  guide/web-animation.md
  guide/web-scene.md
  reference/images/add_proto.png
  reference/images/scene_tree_with_protos.png
Labels: obsolete
