Repository omichel/webots-doc, pull requests merged in 2018-02, with the labels that each got.

#611 Fix remaining issues reported by ESLint
  js/showdown-extensions.js
  js/viewer.js
Labels: enhancement

#610 Add a section about the environments directory
  guide/environments-directory.md
  guide/images/apartment_a.png
  guide/images/apartment_b.png
  guide/images/apartment_c.png
  guide/images/apartment_d.png
  guide/images/factory_a.png
  guide/images/factory_b.png
  guide/images/kitchen.png
  guide/images/spinning_top.png
  guide/menu.md
  guide/sample-webots-applications.md
Labels: enhancement

#617 Remove function parenthesis.
  reference/joystick.md
  reference/motor.md
  reference/positionsensor.md
Labels: enhancement, incorrect

#615 Separate Pioneer AT and DX pages
  guide/images/pioneer3at.png
  guide/images/pioneer3at_real.png
  guide/images/pioneer3dx.png
  guide/images/pioneer3dx_real.png
  guide/images/pioneer3dx_servos.png
  guide/menu.md
  guide/robots.md
  guide/using-the-pioneer-3-at-and-pioneer-3-dx-robots.md
  guide/using-the-pioneer-3-at-robot.md
  guide/using-the-pioneer-3-dx-robot.md
Labels: enhancement

#627 Fix the speaked items
  reference/speaker.md
Labels: incorrect

#628 Merge master to webots-r2018-revision-1
  reference/speaker.md
Labels: update

#618 Pioneer example description
  guide/images/pioneer3at.png
  guide/images/pioneer3at_avoidance.png
  guide/images/pioneer3at_sonars.png
  guide/images/pioneer3at_wheels.png
  guide/images/pioneer3dx.png
  guide/images/pioneer3dx_collision_avoidance.png
  guide/images/pioneer3dx_example.png
  guide/images/pioneer3dx_gripper.png
  guide/images/pioneer3dx_led.png
  guide/images/pioneer3dx_matlab.png
  guide/images/pioneer3dx_servos.png
  guide/images/pioneer3dx_with_kinect.png
  guide/using-the-pioneer-3-at-robot.md
  guide/using-the-pioneer-3-dx-robot.md
Labels: enhancement

#623 More Modern Sidebar
  css/webots-doc.css
  js/viewer.js
Labels: enhancement

#622 Thymio II documentation standardization
  guide/images/thymio2.png
  guide/images/thymio2_ball.png
  guide/images/thymio2_example.png
  guide/images/thymio2_pen.png
  guide/using-the-thymio-ii-robot.md
Labels: enhancement

#630 Merge base graphical geometries samples
  guide/geometries.md
  guide/images/geometric_primitives.png
  guide/images/polygons.png
Labels: enhancement

#632 Fix typo.
  guide/geometries.md
Labels: incorrect

#631 Nao standardization
  guide/images/nao.png
  guide/images/nao_challenge.png
  guide/images/nao_demo.png
  guide/images/nao_example.png
  guide/images/nao_get_the_candies.png
  guide/images/nao_get_the_candies_with_2_robots.png
  guide/images/nao_indoors.png
  guide/images/nao_play_a_movie.png
  guide/images/nao_play_with_me.png
  guide/images/nao_robocup.png
  guide/images/nao_vs_robotis-op2.png
  guide/images/nao_without_camera.png
  guide/using-the-nao-robot.md
Labels: enhancement

#637 Fix doc "top" height
  doc.php
  js/viewer.js
Labels: incorrect

#639 Fixed image name and referencing for billboards
  automobile/billboard.md
  automobile/images/billboard.png
Labels: enhancement

#640 Fix accordion symbols
  css/webots-doc.css
Labels: incorrect

#633 Better robot menu
  guide/images/e-puck.png
  guide/images/nao_short.png
  guide/menu.md
  guide/robots.md
Labels: enhancement

#629 E-puck standardization
  guide/images/e-puck_botstudio_example.png
  guide/images/e-puck_cross-compilation.png
  guide/images/e-puck_example.png
  guide/images/e-puck_kinematic.png
  guide/images/e-puck_line.png
  guide/images/e-puck_line_demo.png
  guide/images/e-puck_sensors_and_leds.png
  guide/using-the-e-puck-robot.md
Labels: enhancement

#636 Creating the Aibo ERS7 doc page
  guide/images/aibo_ers7.png
  guide/images/aibo_ers7_distance_sensors.png
  guide/images/aibo_ers7_example.png
  guide/images/aibo_ers7_motors.png
  guide/menu.md
  guide/real-robots.md
  guide/robots.md
  guide/using-the-aibo-ers7-robot.md
Labels: enhancement

#634 Remove redundant worlds from Real Robot samples
  guide/real-robots.md
Labels: enhancement

#645 Document OSM importer road filter
  automobile/a-typical-openstreetmap-importer-configuration-file.md
  automobile/openstreetmap-importer.md
Labels: enhancement

#648 Fix Table <code> Problems
  automobile/images/osm_gui.png
  css/webots-doc.css
Labels: incorrect

#647 Enhance SUMO Traffic Lights Explanation
  automobile/images/sumo_traffic_light.png
  automobile/scenario-creation-tutorial.md
  automobile/sumo-interface.md
  css/webots-doc.css
Labels: enhancement

#646 Supervisor draw trail example
  guide/how-to.md
  guide/images/supervisor_draw_trail.png
Labels: enhancement

#649 Move spinning_top.wbt to howto section.
  guide/environments-directory.md
  guide/how-to.md
Labels: enhancement

#650 Update kitchen screenshot
  guide/images/kitchen.png
Labels: enhancement

#641 Creating the IPR doc page
  guide/images/ipr.png
  guide/images/ipr_collaboration.png
  guide/images/ipr_cube.png
  guide/images/ipr_factory.png
  guide/images/ipr_models.png
  guide/images/ipr_motors.png
  guide/images/ipr_short.png
  guide/menu.md
  guide/real-robots.md
  guide/robots.md
  guide/using-the-ipr-robot.md
Labels: enhancement

#651 Add doc about the e-puck slowdown issue resolution
  guide/using-the-e-puck-robot.md
Labels: enhancement

#652 Merge master to webots-r2018a-revision-1
  automobile/a-typical-openstreetmap-importer-configuration-file.md
  automobile/images/osm_gui.png
  automobile/images/sumo_traffic_light.png
  automobile/openstreetmap-importer.md
  automobile/scenario-creation-tutorial.md
  automobile/sumo-interface.md
  css/webots-doc.css
  guide/images/aibo_ers7.png
  guide/images/aibo_ers7_distance_sensors.png
  guide/images/aibo_ers7_example.png
  guide/images/aibo_ers7_motors.png
  guide/images/e-puck.png
  guide/images/e-puck_botstudio_example.png
  guide/images/e-puck_cross-compilation.png
  guide/images/e-puck_example.png
  guide/images/e-puck_kinematic.png
  guide/images/e-puck_line.png
  guide/images/e-puck_line_demo.png
  guide/images/e-puck_sensors_and_leds.png
  guide/images/ipr.png
  guide/images/ipr_collaboration.png
  guide/images/ipr_cube.png
  guide/images/ipr_factory.png
  guide/images/ipr_models.png
  guide/images/ipr_motors.png
  guide/images/ipr_short.png
  guide/images/nao_short.png
  guide/menu.md
  guide/real-robots.md
  guide/robots.md
  guide/using-the-aibo-ers7-robot.md
  guide/using-the-e-puck-robot.md
  guide/using-the-ipr-robot.md
Labels: update

#653 Merge webots-r2018a-revision-1 to develop
  automobile/a-typical-openstreetmap-importer-configuration-file.md
  automobile/images/osm_gui.png
  automobile/images/sumo_traffic_light.png
  automobile/openstreetmap-importer.md
  automobile/scenario-creation-tutorial.md
  automobile/sumo-interface.md
  css/webots-doc.css
  guide/environments-directory.md
  guide/how-to.md
  guide/images/aibo_ers7.png
  guide/images/aibo_ers7_distance_sensors.png
  guide/images/aibo_ers7_example.png
  guide/images/aibo_ers7_motors.png
  guide/images/e-puck.png
  guide/images/e-puck_botstudio_example.png
  guide/images/e-puck_cross-compilation.png
  guide/images/e-puck_example.png
  guide/images/e-puck_kinematic.png
  guide/images/e-puck_line.png
  guide/images/e-puck_line_demo.png
  guide/images/e-puck_sensors_and_leds.png
  guide/images/ipr.png
  guide/images/ipr_collaboration.png
  guide/images/ipr_cube.png
  guide/images/ipr_factory.png
  guide/images/ipr_models.png
  guide/images/ipr_motors.png
  guide/images/ipr_short.png
  guide/images/kitchen.png
  guide/images/nao_short.png
  guide/images/supervisor_draw_trail.png
  guide/menu.md
  guide/real-robots.md
  guide/robots.md
  guide/using-the-aibo-ers7-robot.md
  guide/using-the-e-puck-robot.md
  guide/using-the-ipr-robot.md
Labels: update

#654 Fixed typo in tutorial 4
  guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: incorrect

#655 Fixed second typo in tutorial 4
  guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: incorrect

#656 Improve inverted_pendulum.wbt rendering (lights and materials)
  guide/images/inverted_pendulum.png
Labels: enhancement

#658 Add an example about creating a custom HTML robot window
  guide/how-to.md
  guide/images/custom_html_robot_window.png
Labels: enhancement

#660 Fix Indentation In Compass Example
  reference/compass.md
Labels: incorrect

#662 Fix misc issues in the IPR section.
  guide/images/ipr.png
  guide/images/ipr_motors.png
  guide/images/ipr_short.png
  guide/using-the-ipr-robot.md
Labels: enhancement, incorrect

#663 Cross-book hyperlink support
  automobile/introduction.md
  automobile/openstreetmap-importer.md
  automobile/road-segments.md
  guide/computer-peripherals.md
  guide/going-further.md
  guide/how-to.md
  guide/modeling.md
  guide/programming.md
  guide/using-the-e-puck-robot.md
  guide/webots-faq.md
  js/viewer.js
  reference/ros-api.md
  reference/supervisor.md
  tests/test_references.py
Labels: enhancement
