Repository omichel/webots-doc, pull requests merged in 2018-07, with the labels that each got.

#914 Update nao motor limits.
  guide/scenes/nao/nao.meta.json
Labels: update

#918 Update release date in the blog
  blog/Webots-2018-b-release.md
Labels: incorrect

#919 Remove reference to the OgreMaterialConverter.py
  reference/appearance.md
Labels: update

#920 Correct some obsolete blog info
  blog/Webots-2018-b-release.md
Labels: obsolete

#921 Enhancement OSM & SUMO conversion
  automobile/scenario-creation-tutorial.md
Labels: enhancement, update

#927 Added Windows SmartScreen instructions
  guide/images/windows_smartscreen_1.png
  guide/images/windows_smartscreen_2.png
  guide/installation-procedure.md
Labels: OS specific, enhancement

#928 Improved Contribute Link
  js/viewer.js
Labels: enhancement

#930 PBR: LED support
  reference/led.md
  reference/pbrappearance.md
Labels: enhancement

#931 Hofitx GPS speedResolution default value
  reference/gps.md
Labels: incorrect

#938 Enhancement motor set acceleration
  reference/motor.md
Labels: enhancement

#939 Fix function name consistency between code and documentation
  reference/utility-functions.md
Labels: enhancement
