Repository omichel/webots-doc, pull requests merged in 2018-05, with the labels that each got.

#817 Hotfix: broken anchors in firefox
  css/webots-doc.css
  js/viewer.js
Labels: incorrect

#818 Improve anchor scroll
  css/webots-doc.css
  js/viewer.js
Labels: enhancement, incorrect

#798 Very hotfix: Add fallback for the dependencies.txt mechanism.
  dependencies_fallback.txt
  doc.php
Labels: incorrect

#819 Hotfix doc backward compatibility.
  doc.php
Labels: incorrect

#806 Enhancement support ubuntu 18.04
  automobile/openstreetmap-importer.md
  guide/installation-procedure.md
  guide/system-requirements.md
  guide/using-python.md
Labels: update

#825 Add a WordlInfo.randomSeed field
  guide/modeling.md
  reference/worldinfo.md
Labels: enhancement

#821 Enhancement Input Device API
  reference/cpp-api.md
  reference/java-api.md
  reference/matlab-api.md
  reference/python-api.md
  reference/robot.md
  reference/ros-api.md
Labels: enhancement

#828 Update Nao documentation to reflect the removeal of NAOqi
  guide/images/robots/nao/nao.wbt.png
  guide/images/robots/nao/nao_get_the_candies_with_2_robots.wbt.png
  guide/images/robots/nao/nao_play_a_movie.wbt.png
  guide/images/robots/nao/nao_play_with_me.wbt.png
  guide/images/robots/nao/nao_without_camera.wbt.png
  guide/nao.md
  guide/using-matlab.md
  guide/using-visual-cpp-with-webots.md
Labels: update

#833 Improve Windows Python Instructions
  guide/using-python.md
Labels: incorrect

#827 macOS: Migrate from QtWebKit to QtWebEngine
  css/main.macos.css
  local_exporter.py
Labels: enhancement

#831 Improve API headers
  automobile/car-library.md
  automobile/driver-library.md
  css/webots-doc.css
  guide/robotis-op2.md
  js/showdown-extensions.js
  js/viewer.js
  reference/accelerometer.md
  reference/brake.md
  reference/camera.md
  reference/compass.md
  reference/connector.md
  reference/device.md
  reference/differentialwheels.md
  reference/display.md
  reference/distancesensor.md
  reference/emitter.md
  reference/gps.md
  reference/gyro.md
  reference/inertialunit.md
  reference/joystick.md
  reference/keyboard.md
  reference/led.md
  reference/lidar.md
  reference/lightsensor.md
  reference/motion.md
  reference/motor.md
  reference/mouse.md
  reference/pen.md
  reference/positionsensor.md
  reference/radar.md
  reference/rangefinder.md
  reference/receiver.md
  reference/robot.md
  reference/speaker.md
  reference/supervisor.md
  reference/touchsensor.md
  tests/test_references.py
  tests/test_titles.py
Labels: enhancement

#836 Fix and check that hyperlinks are marked as tags only on purpose
  guide/using-ros.md
  tests/test_hyperlinks.py
Labels: incorrect

#837 Fixed missing units for motor API
  reference/linearmotor.md
  reference/motor.md
  reference/rotationalmotor.md
Labels: enhancement

#839 `[mM]atlab` to `MATLAB`
  guide/cpp-java-python.md
  guide/general-bugs.md
  guide/nao.md
  guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  guide/webots-licenses.md
  guide/youbot.md
  js/viewer.js
  reference/accelerometer.md
  reference/brake.md
  reference/camera.md
  reference/compass.md
  reference/connector.md
  reference/device.md
  reference/differentialwheels.md
  reference/display.md
  reference/distancesensor.md
  reference/emitter.md
  reference/gps.md
  reference/gyro.md
  reference/inertialunit.md
  reference/joystick.md
  reference/keyboard.md
  reference/led.md
  reference/lidar.md
  reference/lightsensor.md
  reference/matlab-api.md
  reference/menu.md
  reference/motion.md
  reference/motor.md
  reference/mouse.md
  reference/nodes-and-functions.md
  reference/other-apis.md
  reference/pen.md
  reference/positionsensor.md
  reference/radar.md
  reference/rangefinder.md
  reference/receiver.md
  reference/robot.md
  reference/speaker.md
  reference/supervisor.md
  reference/touchsensor.md
  tests/test_hyperlinks.py
Labels: enhancement, incorrect

#835 SMAA instead of MSAA (doc)
  guide/known-bugs.md
  guide/mac-os.md
  guide/menu.md
  guide/preferences.md
  reference/camera.md
Labels: enhancement

#843 Robot component: Fix device name wrap
  css/webots-doc.css
Labels: enhancement

#845 Feature Disable Viewpoint Change
  guide/the-user-interface.md
Labels: enhancement

#844 HDR (doc)
  reference/camera.md
  reference/light.md
  reference/spotlight.md
  reference/viewpoint.md
Labels: enhancement

#848 Update data type in ROS API documentation
  reference/ros-api.md
Labels: incorrect
